---
title: Lady Whincups an English flower farm growing and selling beautiful seasonal
  flowers
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
url: https://ladywhincups.com
enforce_ssl: https://ladywhincups.com
baseurl: 
google_analytics_key: 
logo: "/siteicon.png"
description: An English Flower Farm growing and selling beautiful seasonal flowers,
  located in the Alde Valley.
twitter: https://twitter.com/JennyMaddenLW
facebook: https://www.facebook.com/Lady-Whincups-472378562953894/
pinterest: https://uk.pinterest.com/18884909ec5d5b8/
instagram: https://www.instagram.com/ladywhincups/
permalink: pretty
gems:
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
_comments:
  background_image: Image shown behind the content.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
